//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Invoice
    {
        public int ID_Client_Invoice { get; set; }
        public string ID_Client { get; set; }
        public string Company_Name { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string ID_Country { get; set; }
        public long ID_Reservation { get; set; }
    }
}
