//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destination_Supplier
    {
        public long ID_Destination { get; set; }
        public int ID_Supplier { get; set; }
        public string ID_Language { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Mail { get; set; }
        public string Terms { get; set; }
    }
}
