//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public long ID_Rate { get; set; }
        public long ID_Destination_Output { get; set; }
        public long ID_Destination_Arrival { get; set; }
        public System.DateTime Date_Start { get; set; }
        public System.DateTime Date_End { get; set; }
        public int ID_Supplier { get; set; }
        public string ID_Currency { get; set; }
        public decimal VAT { get; set; }
        public bool Active { get; set; }
    }
}
