//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public long ID_Reservation { get; set; }
        public string Locator { get; set; }
        public Nullable<System.DateTime> Date_Record { get; set; }
        public Nullable<System.DateTime> Date_Output { get; set; }
        public Nullable<System.DateTime> Date_Arrival { get; set; }
        public Nullable<long> ID_Destination_Output { get; set; }
        public Nullable<long> ID_Destination_Arrival { get; set; }
        public string FlightNumber_Output { get; set; }
        public string FlightNumber_Arrival { get; set; }
        public string Name_Accommodation { get; set; }
        public string Address_Accommodation { get; set; }
        public Nullable<int> ID_Supplier { get; set; }
        public Nullable<decimal> Margin { get; set; }
        public Nullable<int> ID_MarginType { get; set; }
        public Nullable<decimal> Price_Supplier { get; set; }
        public Nullable<decimal> Price_SubTotal { get; set; }
        public Nullable<decimal> Price_Total { get; set; }
        public Nullable<decimal> Price_Discounts { get; set; }
        public Nullable<int> Passengers { get; set; }
        public Nullable<int> Suitcase { get; set; }
        public Nullable<int> Hand_Bags { get; set; }
        public Nullable<int> E_J_Time { get; set; }
        public Nullable<int> Cycles { get; set; }
        public Nullable<int> Golf_Bags { get; set; }
        public Nullable<int> Child_Safety { get; set; }
        public Nullable<int> Child_Booster { get; set; }
        public Nullable<decimal> Price_Suitcase { get; set; }
        public Nullable<decimal> Price_Hand_Bags { get; set; }
        public Nullable<decimal> Price_Cycles { get; set; }
        public Nullable<decimal> Price_Golf_Bags { get; set; }
        public Nullable<decimal> Price_Child_Safety { get; set; }
        public Nullable<decimal> Price_Child_Booster { get; set; }
        public Nullable<decimal> Price_Booking_Fee { get; set; }
        public string ID_Currency { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<int> ID_Reservation_Satus { get; set; }
        public string IP { get; set; }
        public string Client_Note { get; set; }
        public string ID_Client { get; set; }
    }
}
