//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TransfersEntities : DbContext
    {
        public TransfersEntities()
            : base("name=TransfersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Client> Client { get; set; }
        public DbSet<Client_Invoice> Client_Invoice { get; set; }
        public DbSet<Country> Country { get; set; }
        public DbSet<Currency> Currency { get; set; }
        public DbSet<Destination> Destination { get; set; }
        public DbSet<Destination_Supplier> Destination_Supplier { get; set; }
        public DbSet<Group> Group { get; set; }
        public DbSet<Language> Language { get; set; }
        public DbSet<Language_Text> Language_Text { get; set; }
        public DbSet<MarginType> MarginType { get; set; }
        public DbSet<Rate> Rate { get; set; }
        public DbSet<Rate_Language> Rate_Language { get; set; }
        public DbSet<Rate_Vehicle> Rate_Vehicle { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<Reservation_Status> Reservation_Status { get; set; }
        public DbSet<Reservation_Terms> Reservation_Terms { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Vehicle> Vehicle { get; set; }
        public DbSet<Vehicle_Language> Vehicle_Language { get; set; }
        public DbSet<Zone> Zone { get; set; }
    }
}
