//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public long ID_Vehicle { get; set; }
        public string URL_Image { get; set; }
        public int Passengers { get; set; }
        public int Suitcase { get; set; }
        public int Hand_Bags { get; set; }
        public int E_J_Time { get; set; }
        public int Cycles { get; set; }
        public int Golf_Bags { get; set; }
        public int Child_Safety { get; set; }
        public int Child_Booster { get; set; }
        public int ID_Group { get; set; }
    }
}
