//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransfersLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle_Language
    {
        public long ID_Vehicle { get; set; }
        public string ID_Language { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Terms { get; set; }
    }
}
